services:
  dashd:
    image: dashd:latest
    build: .
    container_name: dashd
    restart: unless-stopped
    tty: true
    environment:
      - PORT=4100
      - MMTX_API_URL=host.docker.internal:9997/v3
      - WUUK_API_KEY
      - WYZE1_API_KEY
      - WYZE2_API_KEY
    volumes:
      - ./src:/app/src:ro
    ports:
      - 4100:4100
    extra_hosts:
      - host.docker.internal:host-gateway
      - ing-wuuk.local:$WUUK_LOCAL_IP
      - ing-wyze-1.local:$WYZE1_LOCAL_IP
      - ing-wyze-2.local:$WYZE2_LOCAL_IP
    networks:
      tunnelnet:
        ipv4_address: 172.19.0.3

networks:
  tunnelnet:
    external: true
    name: tunnelnet
